# Generated by Django 4.2.1 on 2023-06-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradore',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
    ]
