# Generated by Django 4.2.1 on 2023-07-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_colaboradore_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradore',
            name='situacao',
            field=models.CharField(default='Ativo', max_length=7),
        ),
    ]
