# Generated by Django 4.2.1 on 2023-07-10 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0012_delete_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.produtos')),
            ],
        ),
    ]
