# Generated by Django 4.2.1 on 2023-07-11 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_baixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixa',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
