# Generated by Django 4.2.1 on 2023-07-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_delete_estoque'),
        ('estoque', '0004_movimentacao_estoque_delete_baixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao_estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.produtos'),
        ),
    ]
