# Generated by Django 4.2.1 on 2023-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_movimentacao_estoque_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao_estoque',
            name='tipo',
            field=models.CharField(choices=[('Saída', 'Saída'), ('Entrada', 'Entrada')], default='Entrada', max_length=7),
        ),
    ]
