# Generated by Django 4.2.1 on 2023-07-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_alter_produtos_tipo'),
        ('estoque', '0007_rename_autor_movimentacao_estoque_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos'),
        ),
    ]
