# Generated by Django 4.2.1 on 2023-06-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produtos_cod_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
    ]
