# Generated by Django 4.2.1 on 2023-06-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produtos_cod_barras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='situacao',
        ),
    ]
