# Generated by Django 4.2.1 on 2023-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_produtos_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='tipo',
            field=models.CharField(default='Alimento', max_length=20),
        ),
    ]
