# Generated by Django 4.2.1 on 2023-07-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produtos_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
