# Generated by Django 4.2.1 on 2023-07-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_produtos_situacao_alter_produtos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='cod_barras',
            field=models.CharField(max_length=13),
        ),
    ]
