# Generated by Django 4.2.1 on 2023-07-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_estoque'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
