# Generated by Django 4.2.1 on 2023-07-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_alter_produtos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='situacao',
            field=models.CharField(default='Ativo', max_length=7),
        ),
    ]
