# Generated by Django 4.2.1 on 2023-06-15 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0002_colaboradore_situacao'),
        ('produtos', '0002_alter_produtos_cod_barras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colaboradores.colaboradore')),
                ('produto', models.ManyToManyField(to='produtos.produtos')),
            ],
        ),
    ]
