# Generated by Django 4.2.1 on 2023-06-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='produto',
        ),
    ]
