# Generated by Django 4.2.1 on 2023-06-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produtos_cod_barras'),
        ('compras', '0002_remove_compra_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('compra_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compra')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.produtos')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='produtos',
            field=models.ManyToManyField(through='compras.ItemCompra', to='produtos.produtos'),
        ),
    ]
