# Generated by Django 4.2.1 on 2023-06-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_itemcompra_compra_produtos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcompra',
            old_name='compra_id',
            new_name='compra',
        ),
    ]
