# Generated by Django 4.2.1 on 2023-06-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_rename_compra_id_itemcompra_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcompra',
            old_name='produto_id',
            new_name='produto',
        ),
    ]
