# Generated by Django 4.2.1 on 2023-06-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_rename_produto_id_itemcompra_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='produtos',
        ),
        migrations.DeleteModel(
            name='ItemCompra',
        ),
    ]
