# Generated by Django 4.2.1 on 2023-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_itemcompra_compra_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
        ),
    ]
