# Generated by Django 4.2.1 on 2023-07-11 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_itemcompra_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
