# Generated by Django 4.2.1 on 2023-07-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_compra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
